# values.yaml for ArgoCD Helm installation - Local Development Setup
server:
  extraArgs:
    - --insecure # Acceptable for local development
  service:
    type: ClusterIP # Changed to ClusterIP for local setup

  ingress:
    enabled: false # Disabled for local setup

  config:
    repositories: |
      - url: https://kubernetes.github.io/ingress-nginx
        name: ingress-nginx
        type: helm
      - url: https://prometheus-community.github.io/helm-charts
        name: prometheus
        type: helm

  rbacConfig:
    policy.default: role:readonly # Keeping this for basic security

# Disabled HA components for local setup
redis-ha:
  enabled: false

controller:
  replicas: 1

repoServer:
  replicas: 1

applicationSet:
  enabled: true # Keeping this enabled as it's useful even in local setup
