apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-apps-set
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/ivankovnatsky/argocd-test
        revision: main
        files:
          - path: apps/nginx-ingress/config.json
  template:
    metadata:
      name: '{{.releaseName}}'
      namespace: argocd
    spec:
      project: '{{.project}}'
      source:
        repoURL: '{{.repoURL}}'
        targetRevision: '{{.version}}'
        chart: '{{.chart}}'
        helm:
          releaseName: '{{.releaseName}}'
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
