apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-apps-set
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/ivankovnatsky/argocd-test
        revision: main
        directories:
          - path: apps/*
        files:
          - path: "apps/*/metadata.yaml"
  template:
    metadata:
      name: '{{path[1]}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{version}}'
        chart: '{{chart}}'
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
